[workspace]
members = [
	"metrics-fn",
	"metrics-fn-codegen",
	"metrics-fn-prometheus",
	"metrics-fn-log",
	"metrics-fn-example",
	"metrics-fn-example-prometheus",
]

[profile.release]
lto = true
strip = true